const commonRoute = {
  postsByType: "/post/:type",
  login: "/login",
  signup: "/signup",
  register: "/:type/signup",
  registerDetails: "/organization/:type/signup",
  typography: "/typography",
  topConference: "/conference",
  libraryTypePage: "/:cId/:pageType",
  conference: "/conference",
  conferenceDetail: "/conference/:eventID",
  allTrendingResearchPredio: "/all-trending-research-presentations",
  topResearchers: "/top-researchers",
  handleRedirect: "/handleRedirect",
  officeBearer: "/conference/:eventID/office-bearer",
  findSession: "/conference/:eventID/find-session",
  discussions: "/discussions",
  discussionsDetails: "/discussions/:discussionID/discussion-details/:qId",
  discussionsTypes: "/discussions/:discussionType",
  findSessionDetails: "/conference/:eventID/find-session/:sessionID",
  presentationDetails: "/presentations/:eventID/:postID/:type",
  organizationProfile: "/organization-profile/:type",
  publishNewPost: "/publish-new-post",
  latestPosts: "/latest-posts",
  sessionExpired: "/session-expired",
  invalidToken: "/invalid-token",
  // posts: "/posts/:pType",
};

export { commonRoute };
